2025-04-27 05:04:08 [WARNING] Config file not found, using defaults
2025-04-27 05:04:08 [ERROR] Falha geral: [Errno 2] No such file or directory: 'checkout.html'
Traceback (most recent call last):
  File "C:\Users\Paulo\Desktop\Phantom\formjacker\form_injector.py", line 357, in inject_payload
    html = Path(html_path).read_text(encoding="utf-8")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'checkout.html'
2025-04-27 05:04:08 [INFO] Execução completa em 0.00s
2025-04-27 05:16:55 [ERROR] Falha geral: [Errno 2] No such file or directory: 'checkout.html'
Traceback (most recent call last):
  File "C:\Users\Paulo\Desktop\Phantom\formjacker\form_injector.py", line 357, in inject_payload
    html = Path(html_path).read_text(encoding="utf-8")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'checkout.html'
2025-04-27 05:17:35 [ERROR] Falha geral: [Errno 2] No such file or directory: 'checkout.html'
Traceback (most recent call last):
  File "C:\Users\Paulo\Desktop\Phantom\formjacker\form_injector.py", line 357, in inject_payload
    html = Path(html_path).read_text(encoding="utf-8")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'checkout.html'
2025-04-27 05:17:49 [ERROR] Falha geral: [Errno 2] No such file or directory: 'checkout.html'
Traceback (most recent call last):
  File "C:\Users\Paulo\Desktop\Phantom\formjacker\form_injector.py", line 357, in inject_payload
    html = Path(html_path).read_text(encoding="utf-8")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'checkout.html'
2025-04-27 05:18:10 [ERROR] TLS pinning error: [Errno 11001] getaddrinfo failed
2025-04-27 05:18:10 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:18:11 [ERROR] GET form_url falhou: 404
2025-04-27 05:18:24 [ERROR] TLS pinning error: [Errno 11001] getaddrinfo failed
2025-04-27 05:18:24 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:18:25 [ERROR] GET form_url falhou: 404
2025-04-27 05:18:47 [ERROR] TLS pinning error: [Errno 11001] getaddrinfo failed
2025-04-27 05:18:47 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:18:47 [ERROR] GET form_url falhou: 404
2025-04-27 05:19:07 [ERROR] TLS pinning error: [Errno 11001] getaddrinfo failed
2025-04-27 05:19:07 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:19:07 [ERROR] GET form_url falhou: 404
2025-04-27 05:19:31 [ERROR] TLS pinning error: [Errno 11001] getaddrinfo failed
2025-04-27 05:19:31 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:19:31 [ERROR] GET form_url falhou: 404
2025-04-27 05:21:57 [ERROR] TLS pinning error: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
2025-04-27 05:21:57 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:21:57 [ERROR] GET form_url falhou: 404
2025-04-27 05:22:18 [ERROR] TLS pinning error: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
2025-04-27 05:22:18 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:22:19 [ERROR] GET form_url falhou: 404
2025-04-27 05:22:30 [ERROR] TLS pinning error: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
2025-04-27 05:22:30 [ERROR] TLS pinning falhou, abortando upload
2025-04-27 05:22:31 [ERROR] GET form_url falhou: 404
